name: Python unit tests

env:
  COMET_API_KEY: ${{ secrets.COMET_API_KEY }}

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root --with dev

      - name: Set PYTHONPATH to include src
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

      - name: Run tests with pyautogui
        run: |
          sudo apt-get install xvfb
          xvfb-run -a -s "-screen 0 640x480x8" poetry run pytest

      - name: Run pre-commit
        run: |
          poetry run pre-commit run --all-files
        continue-on-error: true
